/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
*/

import React, { useRef, useEffect } from 'react';
import { useGLTF } from '@react-three/drei/useGLTF';

export default function Model(props) {
  const group = useRef();
  const { nodes } = useGLTF('/fountain.gltf');
  useEffect(() => {
    group.current.rotation.x = 29.85;
  }, []);
  return (
    <group ref={group} {...props} dispose={null} receiveShadow castShadow>
      <group position={[-193.28, -188, 4]}>
        <mesh material={nodes.mesh_0.material} geometry={nodes.mesh_0.geometry} />
        <mesh material={nodes.mesh_0_1.material} geometry={nodes.mesh_0_1.geometry} />
        <mesh material={nodes.mesh_0_2.material} geometry={nodes.mesh_0_2.geometry} />
        <mesh material={nodes.mesh_0_3.material} geometry={nodes.mesh_0_3.geometry} />
        <mesh material={nodes.mesh_0_4.material} geometry={nodes.mesh_0_4.geometry} />
        <mesh material={nodes.mesh_0_5.material} geometry={nodes.mesh_0_5.geometry} />
        <mesh material={nodes.mesh_0_6.material} geometry={nodes.mesh_0_6.geometry} />
        <mesh material={nodes.mesh_0_7.material} geometry={nodes.mesh_0_7.geometry} />
        <mesh material={nodes.mesh_0_8.material} geometry={nodes.mesh_0_8.geometry} />
        <mesh material={nodes.mesh_0_9.material} geometry={nodes.mesh_0_9.geometry} />
        <mesh material={nodes.mesh_0_10.material} geometry={nodes.mesh_0_10.geometry} />
        <mesh material={nodes.mesh_0_11.material} geometry={nodes.mesh_0_11.geometry} />
        <mesh material={nodes.mesh_0_12.material} geometry={nodes.mesh_0_12.geometry} />
        <mesh material={nodes.mesh_0_13.material} geometry={nodes.mesh_0_13.geometry} />
        <mesh material={nodes.mesh_0_14.material} geometry={nodes.mesh_0_14.geometry} />
        <mesh material={nodes.mesh_0_15.material} geometry={nodes.mesh_0_15.geometry} />
        <mesh material={nodes.mesh_0_16.material} geometry={nodes.mesh_0_16.geometry} />
        <mesh material={nodes.mesh_0_17.material} geometry={nodes.mesh_0_17.geometry} />
        <mesh material={nodes.mesh_0_18.material} geometry={nodes.mesh_0_18.geometry} />
        <mesh material={nodes.mesh_0_19.material} geometry={nodes.mesh_0_19.geometry} />
        <mesh material={nodes.mesh_0_20.material} geometry={nodes.mesh_0_20.geometry} />
        <mesh material={nodes.mesh_0_21.material} geometry={nodes.mesh_0_21.geometry} />
        <mesh material={nodes.mesh_0_22.material} geometry={nodes.mesh_0_22.geometry} />
        <mesh material={nodes.mesh_0_23.material} geometry={nodes.mesh_0_23.geometry} />
        <mesh material={nodes.mesh_0_24.material} geometry={nodes.mesh_0_24.geometry} />
        <mesh material={nodes.mesh_0_25.material} geometry={nodes.mesh_0_25.geometry} />
        <mesh material={nodes.mesh_0_26.material} geometry={nodes.mesh_0_26.geometry} />
        <mesh material={nodes.mesh_0_27.material} geometry={nodes.mesh_0_27.geometry} />
        <group position={[189.15, 144.38, 122.89]} rotation={[0, 0, -Math.PI / 2]} scale={[0.25, 0.25, 0.25]}>
          <group position={[24.28, 2.95, 1.35]} rotation={[0, 0, -2.67]} scale={[0.5, 1, 0.5]}>
            <mesh material={nodes.mesh_1.material} geometry={nodes.mesh_1.geometry} />
            <mesh material={nodes.mesh_1_1.material} geometry={nodes.mesh_1_1.geometry} />
          </group>
        </group>
        <group position={[223.58, 271.57, 27.53]} scale={[0.5, 0.5, 0.5]}>
          <group position={[24.28, 2.95, 1.35]} rotation={[0, 0, -2.67]} scale={[0.5, 1, 0.5]}>
            <mesh material={nodes.mesh_2.material} geometry={nodes.mesh_2.geometry} />
            <mesh material={nodes.mesh_2_1.material} geometry={nodes.mesh_2_1.geometry} />
          </group>
        </group>
      </group>
    </group>
  );
}

useGLTF.preload('/fountain.gltf');
