/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
*/

import React, { useRef } from 'react';
import { useGLTF } from '@react-three/drei/useGLTF';

export default function Model(props) {
  const group = useRef();
  const { nodes, materials } = useGLTF('/modelX.glb');
  return (
    <group ref={group} {...props} dispose={null}>
      <group position={[156.71, 94.7, -412.44]}>
        <group rotation={[-3.08, 0.28, 3.12]} scale={[1, 1, 1]}>
          <group rotation={[0, Math.PI / 2, 0]} />
        </group>
      </group>
      <group rotation={[-Math.PI, 0, Math.PI]} scale={[0.02, 0.02, 0.02]}>
        <mesh
          material={materials.MAT_METAL_1}
          geometry={nodes.cityBlock_04_Road.geometry}
          position={[-778.84, -10.34, -2830.43]}
          rotation={[-Math.PI / 2, 0, 0]}
          scale={[2.54, 2.54, 2.54]}
        />
        <mesh
          material={materials.MAT_METAL_1}
          geometry={nodes.cityBlock_04_Sidewalk.geometry}
          position={[-778.84, -15.61, -2830.43]}
          rotation={[-Math.PI / 2, 0, 0]}
          scale={[2.54, 2.54, 2.54]}
        />
        <mesh
          material={materials.MAT_METAL_1}
          geometry={nodes.cityBlock_04_Curb.geometry}
          position={[-1891.84, -14.09, -2830.43]}
          rotation={[-Math.PI / 2, 0, 0]}
          scale={[2.54, 2.54, 2.54]}
        />
        <mesh
          material={materials['Fabric-Linen']}
          geometry={nodes.cityBlock_04_House_A_Shop_Facade.geometry}
          position={[-10083.57, 545.06, -2908.46]}
          rotation={[-Math.PI / 2, 0, 0]}
          scale={[2.54, 2.54, 2.54]}
        />
        <mesh
          material={materials['Fabric-Linen']}
          geometry={nodes.cityBlock_04_House_A_Facade_01.geometry}
          position={[-10122.59, 1687.85, -2908.46]}
          rotation={[-Math.PI / 2, 0, 0]}
          scale={[2.54, 2.54, 2.54]}
        />
        <mesh
          material={materials['Window Edging']}
          geometry={nodes.cityBlock_04_House_A_Windows_Frames.geometry}
          position={[-10083.57, 2604.8, -2908.46]}
          rotation={[-Math.PI / 2, 0, 0]}
          scale={[2.54, 2.54, 2.54]}
        />
        <mesh
          material={materials.Window}
          geometry={nodes.cityBlock_04_House_A_Windows_Glass.geometry}
          position={[-10083.57, 2098.62, -2908.46]}
          rotation={[-Math.PI / 2, 0, 0]}
          scale={[2.54, 2.54, 2.54]}
        />
        <mesh
          material={materials['Fabric-Linen']}
          geometry={nodes.cityBlock_04_House_A_Facade_02.geometry}
          position={[-10142.11, 1703.46, -2908.46]}
          rotation={[-Math.PI / 2, 0, 0]}
          scale={[2.54, 2.54, 2.54]}
        />
        <mesh
          material={materials['Fabric-Linen']}
          geometry={nodes.cityBlock_04_House_B_Facade_02.geometry}
          position={[-7859.16, 1705.44, -2908.46]}
          rotation={[-Math.PI / 2, 0, 0]}
          scale={[2.54, 2.54, 2.54]}
        />
        <mesh
          material={materials['Fabric-Linen_1']}
          geometry={nodes.cityBlock_04_House_B_Facade_01.geometry}
          position={[-7859.16, 1687.85, -2908.46]}
          rotation={[-Math.PI / 2, 0, 0]}
          scale={[2.54, 2.54, 2.54]}
        />
        <mesh
          material={materials.Window}
          geometry={nodes.cityBlock_04_House_B_Windows_Glass.geometry}
          position={[-7859.16, 2090.21, -2908.46]}
          rotation={[-Math.PI / 2, 0, 0]}
          scale={[2.54, 2.54, 2.54]}
        />
        <mesh
          material={materials['Window Edging']}
          geometry={nodes.cityBlock_04_House_B_Windows_Frames.geometry}
          position={[-7859.16, 2597.53, -2908.46]}
          rotation={[-Math.PI / 2, 0, 0]}
          scale={[2.54, 2.54, 2.54]}
        />
        <mesh
          material={materials['Fabric-Linen_1']}
          geometry={nodes.cityBlock_04_House_B_Shop_Facade.geometry}
          position={[-7820.13, 550.31, -2908.46]}
          rotation={[-Math.PI / 2, 0, 0]}
          scale={[2.54, 2.54, 2.54]}
        />
        <mesh
          material={materials['Fabric-Linen_2']}
          geometry={nodes.cityBlock_04_House_C_Shop_Facade.geometry}
          position={[-5736.21, 533.51, -2908.46]}
          rotation={[-Math.PI / 2, 0, 0]}
          scale={[2.54, 2.54, 2.54]}
        />
        <mesh
          material={materials['Fabric-Linen_2']}
          geometry={nodes.cityBlock_04_House_C_Facade_01.geometry}
          position={[-5736.21, 1687.85, -2908.46]}
          rotation={[-Math.PI / 2, 0, 0]}
          scale={[2.54, 2.54, 2.54]}
        />
        <mesh
          material={materials.DefaultMaterial}
          geometry={nodes.cityBlock_04_House_C_Facade_02.geometry}
          position={[-5736.21, 1697.04, -2908.46]}
          rotation={[-Math.PI / 2, 0, 0]}
          scale={[2.54, 2.54, 2.54]}
        />
        <mesh
          material={materials.Window}
          geometry={nodes.cityBlock_04_House_C_Windows_Glass.geometry}
          position={[-5736.21, 2092.98, -2908.46]}
          rotation={[-Math.PI / 2, 0, 0]}
          scale={[2.54, 2.54, 2.54]}
        />
        <mesh
          material={materials['Window Edging']}
          geometry={nodes.cityBlock_04_House_C_Windows_Frames.geometry}
          position={[-5735.93, 2674.45, -2908.46]}
          rotation={[-Math.PI / 2, 0, 0]}
          scale={[2.54, 2.54, 2.54]}
        />
        <mesh
          material={materials['Fabric-Linen_4']}
          geometry={nodes.cityBlock_04_House_E_Windows_Frames.geometry}
          position={[-1771.57, 2730.85, -2908.46]}
          rotation={[-Math.PI / 2, 0, 0]}
          scale={[2.54, 2.54, 2.54]}
        />
        <mesh
          material={materials['Fabric-Linen']}
          geometry={nodes.cityBlock_04_House_E_Facade_01.geometry}
          position={[-1771.3, 1687.85, -2908.46]}
          rotation={[-Math.PI / 2, 0, 0]}
          scale={[2.54, 2.54, 2.54]}
        />
        <mesh
          material={materials.Window}
          geometry={nodes.cityBlock_04_House_E_Windows_Glass.geometry}
          position={[-1771.3, 2134.84, -2908.46]}
          rotation={[-Math.PI / 2, 0, 0]}
          scale={[2.54, 2.54, 2.54]}
        />
        <mesh
          material={materials['Fabric-Linen']}
          geometry={nodes.cityBlock_04_House_E_Facade_02.geometry}
          position={[-1771.3, 1697.62, -2908.46]}
          rotation={[-Math.PI / 2, 0, 0]}
          scale={[2.54, 2.54, 2.54]}
        />
        <mesh
          material={materials['Fabric-Linen_1']}
          geometry={nodes.cityBlock_04_House_D_Facade_01.geometry}
          position={[-3753.75, 1687.85, -2908.46]}
          rotation={[-Math.PI / 2, 0, 0]}
          scale={[2.54, 2.54, 2.54]}
        />
        <mesh
          material={materials['Fabric-Linen']}
          geometry={nodes.cityBlock_04_House_E_Shop_Facade.geometry}
          position={[-1771.21, 535.49, -2908.46]}
          rotation={[-Math.PI / 2, 0, 0]}
          scale={[2.54, 2.54, 2.54]}
        />
        <mesh
          material={materials['Fabric-Linen_2']}
          geometry={nodes.cityBlock_04_House_D_Facade_02.geometry}
          position={[-3753.75, 1705.44, -2908.46]}
          rotation={[-Math.PI / 2, 0, 0]}
          scale={[2.54, 2.54, 2.54]}
        />
        <mesh
          material={materials['Window Edging']}
          geometry={nodes.cityBlock_04_House_D_Windows_Frames.geometry}
          position={[-3754.03, 2674.45, -2908.46]}
          rotation={[-Math.PI / 2, 0, 0]}
          scale={[2.54, 2.54, 2.54]}
        />
        <mesh
          material={materials.Window}
          geometry={nodes.cityBlock_04_House_D_Windows_Glass.geometry}
          position={[-3748.77, 2097.48, -2908.46]}
          rotation={[-Math.PI / 2, 0, 0]}
          scale={[2.54, 2.54, 2.54]}
        />
        <mesh
          material={materials['Fabric-Linen_1']}
          geometry={nodes.cityBlock_04_House_D_Shop_Facade.geometry}
          position={[-3753.75, 550.31, -2908.46]}
          rotation={[-Math.PI / 2, 0, 0]}
          scale={[2.54, 2.54, 2.54]}
        />
        <mesh
          material={materials['Fabric-Linen_4']}
          geometry={nodes.cityBlock_04_House_F_Windows_Frames.geometry}
          position={[351.65, 2597.53, -2908.46]}
          rotation={[-Math.PI / 2, 0, 0]}
          scale={[2.54, 2.54, 2.54]}
        />
        <mesh
          material={materials['Fabric-Linen_1']}
          geometry={nodes.cityBlock_04_House_F_Facade_02.geometry}
          position={[351.65, 1702.73, -2908.46]}
          rotation={[-Math.PI / 2, 0, 0]}
          scale={[2.54, 2.54, 2.54]}
        />
        <mesh
          material={materials['Fabric-Linen_1']}
          geometry={nodes.cityBlock_04_House_F_Facade_01.geometry}
          position={[351.65, 1687.85, -2908.46]}
          rotation={[-Math.PI / 2, 0, 0]}
          scale={[2.54, 2.54, 2.54]}
        />
        <mesh
          material={materials.Window}
          geometry={nodes.cityBlock_04_House_F_Windows_Glass.geometry}
          position={[365.18, 2087.49, -2908.46]}
          rotation={[-Math.PI / 2, 0, 0]}
          scale={[2.54, 2.54, 2.54]}
        />
        <mesh
          material={materials['Fabric-Linen_1']}
          geometry={nodes.cityBlock_04_House_F_Shop_Facade.geometry}
          position={[390.68, 543.59, -2908.46]}
          rotation={[-Math.PI / 2, 0, 0]}
          scale={[2.54, 2.54, 2.54]}
        />
        <mesh
          material={materials['Fabric-Linen']}
          geometry={nodes.cityBlock_04_House_H_Shop_Facade.geometry}
          position={[4574.22, 535.49, -2908.46]}
          rotation={[-Math.PI / 2, 0, 0]}
          scale={[2.54, 2.54, 2.54]}
        />
        <mesh
          material={materials.Window}
          geometry={nodes.cityBlock_04_House_G_Windows_Glass.geometry}
          position={[2474.61, 2148.32, -2908.46]}
          rotation={[-Math.PI / 2, 0, 0]}
          scale={[2.54, 2.54, 2.54]}
        />
        <mesh
          material={materials.MAT_METAL_1}
          geometry={nodes.cityBlock_04_House_G_Windows_Frames.geometry}
          position={[2474.33, 2730.85, -2908.46]}
          rotation={[-Math.PI / 2, 0, 0]}
          scale={[2.54, 2.54, 2.54]}
        />
        <mesh
          material={materials['Fabric-Linen_4']}
          geometry={nodes.cityBlock_04_House_G_Facade_02.geometry}
          position={[2474.61, 1697.04, -2908.46]}
          rotation={[-Math.PI / 2, 0, 0]}
          scale={[2.54, 2.54, 2.54]}
        />
        <mesh
          material={materials.DefaultMaterial}
          geometry={nodes.cityBlock_04_House_G_Facade_01.geometry}
          position={[2474.61, 1687.85, -2908.46]}
          rotation={[-Math.PI / 2, 0, 0]}
          scale={[2.54, 2.54, 2.54]}
        />
        <mesh
          material={materials.DefaultMaterial}
          geometry={nodes.cityBlock_04_House_G_Shop_Facade.geometry}
          position={[2474.61, 533.51, -2908.46]}
          rotation={[-Math.PI / 2, 0, 0]}
          scale={[2.54, 2.54, 2.54]}
        />
        <mesh
          material={materials['Fabric-Linen']}
          geometry={nodes.cityBlock_04_House_H_Facade_01.geometry}
          position={[4572.86, 1681.43, -2908.46]}
          rotation={[-Math.PI / 2, 0, 0]}
          scale={[2.54, 2.54, 2.54]}
        />
        <mesh
          material={materials['Fabric-Linen_1']}
          geometry={nodes.cityBlock_04_House_I_Facade_01.geometry}
          position={[7709.17, 2718.9, -3507.74]}
          rotation={[-Math.PI / 2, 0, 0]}
          scale={[2.54, 2.54, 2.54]}
        />
        <mesh
          material={materials['Fabric-Linen_1']}
          geometry={nodes.cityBlock_04_House_A_Roof_End.geometry}
          position={[-11207.48, 3941.29, -2908.46]}
          rotation={[-Math.PI / 2, 0, 0]}
          scale={[2.54, 2.54, 2.54]}
        />
        <mesh
          material={materials['Fabric-Linen_1']}
          geometry={nodes.cityBlock_04_Divider_01.geometry}
          position={[-8990.87, 3941.29, -2908.46]}
          rotation={[-Math.PI / 2, 0, 0]}
          scale={[2.54, 2.54, 2.54]}
        />
        <mesh
          material={materials['Fabric-Linen_1']}
          geometry={nodes.cityBlock_04_Divider_02.geometry}
          position={[-6727.44, 3941.29, -2908.46]}
          rotation={[-Math.PI / 2, 0, 0]}
          scale={[2.54, 2.54, 2.54]}
        />
        <mesh
          material={materials['Fabric-Linen_2']}
          geometry={nodes.cityBlock_04_Divider_03.geometry}
          position={[-4744.98, 3941.29, -2908.46]}
          rotation={[-Math.PI / 2, 0, 0]}
          scale={[2.54, 2.54, 2.54]}
        />
        <mesh
          material={materials['Fabric-Linen_1']}
          geometry={nodes.cityBlock_04_Divider_04.geometry}
          position={[-2762.52, 3941.29, -2908.46]}
          rotation={[-Math.PI / 2, 0, 0]}
          scale={[2.54, 2.54, 2.54]}
        />
        <mesh
          material={materials['Fabric-Linen']}
          geometry={nodes.cityBlock_04_Divider_05.geometry}
          position={[-780.07, 3941.29, -2908.46]}
          rotation={[-Math.PI / 2, 0, 0]}
          scale={[2.54, 2.54, 2.54]}
        />
        <mesh
          material={materials['Fabric-Linen_1']}
          geometry={nodes.cityBlock_04_Divider_06.geometry}
          position={[1483.38, 3941.29, -2908.46]}
          rotation={[-Math.PI / 2, 0, 0]}
          scale={[2.54, 2.54, 2.54]}
        />
        <mesh
          material={materials.DefaultMaterial}
          geometry={nodes.cityBlock_04_Divider_07.geometry}
          position={[3465.84, 3941.29, -2908.46]}
          rotation={[-Math.PI / 2, 0, 0]}
          scale={[2.54, 2.54, 2.54]}
        />
        <mesh
          material={materials['Fabric-Linen']}
          geometry={nodes.cityBlock_04_Divider_08.geometry}
          position={[5633.04, 3941.29, -2908.46]}
          rotation={[-Math.PI / 2, 0, 0]}
          scale={[2.54, 2.54, 2.54]}
        />
        <mesh
          material={materials['Fabric-Linen_1']}
          geometry={nodes.cityBlock_04_House_B_Roof_01.geometry}
          position={[-7859.16, 3894.46, -2908.46]}
          rotation={[-Math.PI / 2, 0, 0]}
          scale={[2.54, 2.54, 2.54]}
        />
        <mesh
          material={materials['Fabric-Linen']}
          geometry={nodes.cityBlock_04_House_A_Roof_01.geometry}
          position={[-10099.18, 3894.46, -2908.46]}
          rotation={[-Math.PI / 2, 0, 0]}
          scale={[2.54, 2.54, 2.54]}
        />
        <mesh
          material={materials['Fabric-Linen_2']}
          geometry={nodes.cityBlock_04_House_C_Roof_01.geometry}
          position={[-5735.93, 3894.47, -2908.46]}
          rotation={[-Math.PI / 2, 0, 0]}
          scale={[2.54, 2.54, 2.54]}
        />
        <mesh
          material={materials['Fabric-Linen']}
          geometry={nodes.cityBlock_04_House_H_Facade_02.geometry}
          position={[4572.86, 1697.62, -2908.46]}
          rotation={[-Math.PI / 2, 0, 0]}
          scale={[2.54, 2.54, 2.54]}
        />
        <mesh
          material={materials.Window}
          geometry={nodes.cityBlock_04_House_H_Windows_Glass.geometry}
          position={[4566.58, 2072.24, -2908.46]}
          rotation={[-Math.PI / 2, 0, 0]}
          scale={[2.54, 2.54, 2.54]}
        />
        <mesh
          material={materials['Fabric-Linen_4']}
          geometry={nodes.cityBlock_04_House_H_Windows_Frames.geometry}
          position={[4558.53, 2668.43, -2908.46]}
          rotation={[-Math.PI / 2, 0, 0]}
          scale={[2.54, 2.54, 2.54]}
        />
        <mesh
          material={materials['Fabric-Linen_1']}
          geometry={nodes.cityBlock_04_House_F_Roof_02.geometry}
          position={[351.65, 3716.2, -2908.46]}
          rotation={[-Math.PI / 2, 0, 0]}
          scale={[2.54, 2.54, 2.54]}
        />
        <mesh
          material={materials.MAT_METAL_1}
          geometry={nodes.cityBlock_04_House_H_Roof_02.geometry}
          position={[4558.53, 3716.2, -2908.46]}
          rotation={[-Math.PI / 2, 0, 0]}
          scale={[2.54, 2.54, 2.54]}
        />
        <mesh
          material={materials['Fabric-Linen_2']}
          geometry={nodes.cityBlock_04_House_D_Roof_02.geometry}
          position={[-3754.03, 3779.89, -2908.46]}
          rotation={[-Math.PI / 2, 0, 0]}
          scale={[2.54, 2.54, 2.54]}
        />
        <mesh
          material={materials['Fabric-Linen']}
          geometry={nodes.cityBlock_04_House_E_Roof_01.geometry}
          position={[-1771.57, 3894.47, -2908.46]}
          rotation={[-Math.PI / 2, 0, 0]}
          scale={[2.54, 2.54, 2.54]}
        />
        <mesh
          material={materials['Fabric-Linen_3']}
          geometry={nodes.cityBlock_04_House_I_Shop_Facade.geometry}
          position={[7799.82, 535.49, -3507.74]}
          rotation={[-Math.PI / 2, 0, 0]}
          scale={[2.54, 2.54, 2.54]}
        />
        <mesh
          material={materials['Fabric-Linen_4']}
          geometry={nodes.cityBlock_04_House_I_Windows_Frames.geometry}
          position={[7849.66, 3315.54, -3507.74]}
          rotation={[-Math.PI / 2, 0, 0]}
          scale={[2.54, 2.54, 2.54]}
        />
        <mesh
          material={materials.Window}
          geometry={nodes.cityBlock_04_House_I_Windows_Glass.geometry}
          position={[7795.81, 2720.37, -3507.74]}
          rotation={[-Math.PI / 2, 0, 0]}
          scale={[2.54, 2.54, 2.54]}
        />
        <mesh
          material={materials['Fabric-Linen_1']}
          geometry={nodes.cityBlock_04_House_I_Facade_02.geometry}
          position={[7709.17, 2755.38, -3507.74]}
          rotation={[-Math.PI / 2, 0, 0]}
          scale={[2.54, 2.54, 2.54]}
        />
        <mesh
          material={materials['Fabric-Linen_1']}
          geometry={nodes.cityBlock_04_House_A_Roof_02.geometry}
          position={[-10083.86, 3911.39, -2908.46]}
          rotation={[-Math.PI / 2, 0, 0]}
          scale={[2.54, 2.54, 2.54]}
        />
        <mesh
          material={materials['Fabric-Linen']}
          geometry={nodes.cityBlock_04_House_A_Chimney_01.geometry}
          position={[-9158.02, 4034.71, -2977.28]}
          rotation={[-Math.PI / 2, 0, 0]}
          scale={[2.54, 2.54, 2.54]}
        />
        <mesh
          material={materials['Fabric-Linen']}
          geometry={nodes.cityBlock_04_House_A_Chimney_02.geometry}
          position={[-9158.03, 5056.87, -2977.28]}
          rotation={[-Math.PI / 2, 0, 0]}
          scale={[2.54, 2.54, 2.54]}
        />
        <mesh
          material={materials['Fabric-Linen_1']}
          geometry={nodes.cityBlock_04_House_B_Chimney_01.geometry}
          position={[-5895.57, 3522.34, -2990.17]}
          rotation={[-Math.PI / 2, 0, 0]}
          scale={[2.54, 2.54, 2.54]}
        />
        <mesh
          material={materials['Fabric-Linen_1']}
          geometry={nodes.cityBlock_04_House_B_Chimney_02.geometry}
          position={[-6888.37, 4903.26, -3076.59]}
          rotation={[-Math.PI / 2, 0, 0]}
          scale={[2.54, 2.54, 2.54]}
        />
        <mesh
          material={materials['Fabric-Linen']}
          geometry={nodes.cityBlock_04_House_A_Shop_Sign.geometry}
          position={[-10083.57, 1014.94, -2908.46]}
          rotation={[-Math.PI / 2, 0, 0]}
          scale={[2.54, 2.54, 2.54]}
        />
        <mesh
          material={materials['Fabric-Linen_3']}
          geometry={nodes.cityBlock_04_House_B_Roof_02.geometry}
          position={[-7859.16, 3716.2, -2908.46]}
          rotation={[-Math.PI / 2, 0, 0]}
          scale={[2.54, 2.54, 2.54]}
        />
        <mesh
          material={materials['Fabric-Linen_2']}
          geometry={nodes.cityBlock_04_House_C_Shop_Sign.geometry}
          position={[-5736.21, 880.83, -2908.46]}
          rotation={[-Math.PI / 2, 0, 0]}
          scale={[2.54, 2.54, 2.54]}
        />
        <mesh
          material={materials.DefaultMaterial}
          geometry={nodes.cityBlock_04_House_C_Roof_02.geometry}
          position={[-5735.93, 3779.89, -2908.46]}
          rotation={[-Math.PI / 2, 0, 0]}
          scale={[2.54, 2.54, 2.54]}
        />
        <mesh
          material={materials['Fabric-Linen_1']}
          geometry={nodes.cityBlock_04_House_D_Roof_01.geometry}
          position={[-3753.75, 3894.47, -2908.46]}
          rotation={[-Math.PI / 2, 0, 0]}
          scale={[2.54, 2.54, 2.54]}
        />
        <mesh
          material={materials['Fabric-Linen_4']}
          geometry={nodes.cityBlock_04_House_E_Shop_Sign.geometry}
          position={[-1771.3, 776.61, -2908.46]}
          rotation={[-Math.PI / 2, 0, 0]}
          scale={[2.54, 2.54, 2.54]}
        />
        <mesh
          material={materials.DefaultMaterial}
          geometry={nodes.cityBlock_04_House_G_Shop_Sign.geometry}
          position={[2474.61, 880.83, -2908.46]}
          rotation={[-Math.PI / 2, 0, 0]}
          scale={[2.54, 2.54, 2.54]}
        />
        <mesh
          material={materials['Fabric-Linen_4']}
          geometry={nodes.cityBlock_04_House_H_Shop_Sign.geometry}
          position={[4574.14, 776.61, -2908.46]}
          rotation={[-Math.PI / 2, 0, 0]}
          scale={[2.54, 2.54, 2.54]}
        />
        <mesh
          material={materials['Fabric-Linen_4']}
          geometry={nodes.cityBlock_04_House_I_Shop_Sign.geometry}
          position={[7802.83, 963.22, -3507.74]}
          rotation={[-Math.PI / 2, 0, 0]}
          scale={[2.54, 2.54, 2.54]}
        />
        <mesh
          material={materials['Fabric-Linen']}
          geometry={nodes.cityBlock_04_House_E_Roof_02.geometry}
          position={[-1771.57, 3779.89, -2908.46]}
          rotation={[-Math.PI / 2, 0, 0]}
          scale={[2.54, 2.54, 2.54]}
        />
        <mesh
          material={materials['Fabric-Linen_1']}
          geometry={nodes.cityBlock_04_House_F_Shop_Sign.geometry}
          position={[390.68, 893.87, -2908.46]}
          rotation={[-Math.PI / 2, 0, 0]}
          scale={[2.54, 2.54, 2.54]}
        />
        <mesh
          material={materials['Fabric-Linen_1']}
          geometry={nodes.cityBlock_04_House_F_Roof_01.geometry}
          position={[351.65, 3894.46, -2908.46]}
          rotation={[-Math.PI / 2, 0, 0]}
          scale={[2.54, 2.54, 2.54]}
        />
        <mesh
          material={materials['Fabric-Linen']}
          geometry={nodes.cityBlock_04_House_H_Roof_01.geometry}
          position={[4549.44, 3894.46, -2908.46]}
          rotation={[-Math.PI / 2, 0, 0]}
          scale={[2.54, 2.54, 2.54]}
        />
        <mesh
          material={materials.DefaultMaterial}
          geometry={nodes.cityBlock_04_House_G_Roof_01.geometry}
          position={[2474.33, 3894.47, -2908.46]}
          rotation={[-Math.PI / 2, 0, 0]}
          scale={[2.54, 2.54, 2.54]}
        />
        <mesh
          material={materials['Fabric-Linen_4']}
          geometry={nodes.cityBlock_04_House_G_Roof_02.geometry}
          position={[2474.33, 3779.89, -2908.46]}
          rotation={[-Math.PI / 2, 0, 0]}
          scale={[2.54, 2.54, 2.54]}
        />
        <mesh
          material={materials['Fabric-Linen_2']}
          geometry={nodes.cityBlock_04_House_C_Chimney_01.geometry}
          position={[-4929.12, 4034.71, -2977.28]}
          rotation={[-Math.PI / 2, 0, 0]}
          scale={[2.54, 2.54, 2.54]}
        />
        <mesh
          material={materials['Fabric-Linen_2']}
          geometry={nodes.cityBlock_04_House_C_Chimney_02.geometry}
          position={[-4929.12, 5056.87, -2977.28]}
          rotation={[-Math.PI / 2, 0, 0]}
          scale={[2.54, 2.54, 2.54]}
        />
        <mesh
          material={materials['Fabric-Linen_1']}
          geometry={nodes.cityBlock_04_House_F_Chimney_02.geometry}
          position={[1337.79, 5056.87, -2977.28]}
          rotation={[-Math.PI / 2, 0, 0]}
          scale={[2.54, 2.54, 2.54]}
        />
        <mesh
          material={materials['Fabric-Linen_1']}
          geometry={nodes.cityBlock_04_House_F_Chimney_01.geometry}
          position={[1337.79, 4034.71, -2977.28]}
          rotation={[-Math.PI / 2, 0, 0]}
          scale={[2.54, 2.54, 2.54]}
        />
        <mesh
          material={materials['Fabric-Linen_1']}
          geometry={nodes.cityBlock_04_House_D_Chimney_02.geometry}
          position={[-2914.44, 5056.87, -2977.28]}
          rotation={[-Math.PI / 2, 0, 0]}
          scale={[2.54, 2.54, 2.54]}
        />
        <mesh
          material={materials['Fabric-Linen_1']}
          geometry={nodes.cityBlock_04_House_D_Chimney_01.geometry}
          position={[-2914.44, 4034.71, -2977.28]}
          rotation={[-Math.PI / 2, 0, 0]}
          scale={[2.54, 2.54, 2.54]}
        />
        <mesh
          material={materials['Fabric-Linen']}
          geometry={nodes.cityBlock_04_House_E_Chimney_02.geometry}
          position={[-934.4, 5056.87, -2977.28]}
          rotation={[-Math.PI / 2, 0, 0]}
          scale={[2.54, 2.54, 2.54]}
        />
        <mesh
          material={materials['Fabric-Linen']}
          geometry={nodes.cityBlock_04_House_E_Chimney_01.geometry}
          position={[-934.4, 4034.71, -2977.28]}
          rotation={[-Math.PI / 2, 0, 0]}
          scale={[2.54, 2.54, 2.54]}
        />
        <mesh
          material={materials.DefaultMaterial}
          geometry={nodes.cityBlock_04_House_G_Chimney_01.geometry}
          position={[4299.34, 3522.34, -2990.17]}
          rotation={[-Math.PI / 2, 0, 0]}
          scale={[2.54, 2.54, 2.54]}
        />
        <mesh
          material={materials['Fabric-Linen_2']}
          geometry={nodes.cityBlock_04_House_G_Chimney_02.geometry}
          position={[3306.55, 4903.26, -3076.59]}
          rotation={[-Math.PI / 2, 0, 0]}
          scale={[2.54, 2.54, 2.54]}
        />
        <mesh
          material={materials['Fabric-Linen']}
          geometry={nodes.cityBlock_04_House_H_Chimney_01.geometry}
          position={[4502.28, 3522.34, -2964.37]}
          rotation={[-Math.PI / 2, 0, 0]}
          scale={[2.54, 2.54, 2.54]}
        />
        <mesh
          material={materials['Fabric-Linen']}
          geometry={nodes.cityBlock_04_House_H_Chimney_02.geometry}
          position={[5495.09, 4903.26, -2877.95]}
          rotation={[-Math.PI / 2, 0, 0]}
          scale={[2.54, 2.54, 2.54]}
        />
        <mesh
          material={materials['Fabric-Linen_1']}
          geometry={nodes.cityBlock_04_House_I_Roof.geometry}
          position={[7703.65, 5379.05, -3507.74]}
          rotation={[-Math.PI / 2, 0, 0]}
          scale={[2.54, 2.54, 2.54]}
        />
        <mesh
          material={materials['Fabric-Linen_1']}
          geometry={nodes.cityBlock_04_House_I_Chimney_02.geometry}
          position={[6387.68, 6074.81, -3182.95]}
          rotation={[-Math.PI / 2, 0, 0]}
          scale={[2.54, 2.54, 2.54]}
        />
        <mesh
          material={materials['Fabric-Linen_1']}
          geometry={nodes.cityBlock_04_House_I_Chimney_01.geometry}
          position={[6450.43, 5051.75, -3203.42]}
          rotation={[-Math.PI / 2, 0, 0]}
          scale={[2.54, 2.54, 2.54]}
        />
        <mesh
          material={materials['Fabric-Linen']}
          geometry={nodes.cityBlock_04_Sign_01.geometry}
          position={[-12386.05, 2337.42, -1500.65]}
          rotation={[-Math.PI / 2, 0, 0]}
          scale={[2.54, 2.54, 2.54]}
        />
        <mesh
          material={materials['Fabric-Linen']}
          geometry={nodes.cityBlock_04_Sign_02.geometry}
          position={[4572.86, 2250.27, -2908.46]}
          rotation={[-Math.PI / 2, 0, 0]}
          scale={[2.54, 2.54, 2.54]}
        />
        <mesh
          material={materials.DefaultMaterial}
          geometry={nodes.cityBlock_04_Sign_03.geometry}
          position={[2474.61, 2725.86, -2908.46]}
          rotation={[-Math.PI / 2, 0, 0]}
          scale={[2.54, 2.54, 2.54]}
        />
        <mesh
          material={materials['Fabric-Linen_1']}
          geometry={nodes.cityBlock_04_Sign_04.geometry}
          position={[372.18, 2641.22, -2908.46]}
          rotation={[-Math.PI / 2, 0, 0]}
          scale={[2.54, 2.54, 2.54]}
        />
        <mesh
          material={materials['Fabric-Linen_2']}
          geometry={nodes.cityBlock_04_Sign_05.geometry}
          position={[-5707.52, 2290.03, -2908.46]}
          rotation={[-Math.PI / 2, 0, 0]}
          scale={[2.54, 2.54, 2.54]}
        />
        <mesh
          material={materials['Fabric-Linen_1']}
          geometry={nodes.cityBlock_04_Gutter_01.geometry}
          position={[-8990.87, 1715.89, -2908.46]}
          rotation={[-Math.PI / 2, 0, 0]}
          scale={[2.54, 2.54, 2.54]}
        />
        <mesh
          material={materials['Fabric-Linen_1']}
          geometry={nodes.cityBlock_04_Gutter_02.geometry}
          position={[-6727.44, 1715.89, -2908.46]}
          rotation={[-Math.PI / 2, 0, 0]}
          scale={[2.54, 2.54, 2.54]}
        />
        <mesh
          material={materials['Fabric-Linen_2']}
          geometry={nodes.cityBlock_04_Gutter_03.geometry}
          position={[-4744.98, 1715.89, -2908.46]}
          rotation={[-Math.PI / 2, 0, 0]}
          scale={[2.54, 2.54, 2.54]}
        />
        <mesh
          material={materials['Fabric-Linen_1']}
          geometry={nodes.cityBlock_04_Gutter_004.geometry}
          position={[-2762.52, 1715.89, -2908.46]}
          rotation={[-Math.PI / 2, 0, 0]}
          scale={[2.54, 2.54, 2.54]}
        />
        <mesh
          material={materials['Fabric-Linen']}
          geometry={nodes.cityBlock_04_Gutter_005.geometry}
          position={[-780.07, 1715.89, -2908.46]}
          rotation={[-Math.PI / 2, 0, 0]}
          scale={[2.54, 2.54, 2.54]}
        />
        <mesh
          material={materials['Fabric-Linen_1']}
          geometry={nodes.cityBlock_04_Gutter_006.geometry}
          position={[1483.38, 1715.89, -2908.46]}
          rotation={[-Math.PI / 2, 0, 0]}
          scale={[2.54, 2.54, 2.54]}
        />
        <mesh
          material={materials.DefaultMaterial}
          geometry={nodes.cityBlock_04_Gutter_007.geometry}
          position={[3465.84, 1715.89, -2908.46]}
          rotation={[-Math.PI / 2, 0, 0]}
          scale={[2.54, 2.54, 2.54]}
        />
        <mesh
          material={materials['Fabric-Linen']}
          geometry={nodes.cityBlock_04_Gutter_008.geometry}
          position={[5679.88, 1715.89, -2908.46]}
          rotation={[-Math.PI / 2, 0, 0]}
          scale={[2.54, 2.54, 2.54]}
        />
        <mesh
          material={materials.MAT_METAL_1}
          geometry={nodes.cityBlock_04_Lamp_Light.geometry}
          position={[-11835.52, 961.41, -1735.14]}
          rotation={[-Math.PI / 2, 0, 0]}
          scale={[2.54, 2.54, 2.54]}
        />
        <mesh
          material={materials['Window Edging']}
          geometry={nodes.cityBlock_04_Lamp.geometry}
          position={[-11835.52, 961.41, -1735.14]}
          rotation={[-Math.PI / 2, 0, 0]}
          scale={[2.54, 2.54, 2.54]}
        />
        <mesh
          material={materials.MAT_METAL_1}
          geometry={nodes.cityBlock_04_Lamp_Light001.geometry}
          position={[-6389.76, 961.41, -1735.14]}
          rotation={[-Math.PI / 2, 0, 0]}
          scale={[2.54, 2.54, 2.54]}
        />
        <mesh
          material={materials['Window Edging']}
          geometry={nodes.cityBlock_04_Lamp001.geometry}
          position={[-6389.76, 961.41, -1735.14]}
          rotation={[-Math.PI / 2, 0, 0]}
          scale={[2.54, 2.54, 2.54]}
        />
        <mesh
          material={materials.MAT_METAL_1}
          geometry={nodes.cityBlock_04_Lamp_Light002.geometry}
          position={[-944.01, 961.41, -1735.14]}
          rotation={[-Math.PI / 2, 0, 0]}
          scale={[2.54, 2.54, 2.54]}
        />
        <mesh
          material={materials['Window Edging']}
          geometry={nodes.cityBlock_04_Lamp002.geometry}
          position={[-944.01, 961.41, -1735.14]}
          rotation={[-Math.PI / 2, 0, 0]}
          scale={[2.54, 2.54, 2.54]}
        />
        <mesh
          material={materials.MAT_METAL_1}
          geometry={nodes.cityBlock_04_Lamp_Light003.geometry}
          position={[4501.75, 961.41, -1735.14]}
          rotation={[-Math.PI / 2, 0, 0]}
          scale={[2.54, 2.54, 2.54]}
        />
        <mesh
          material={materials['Window Edging']}
          geometry={nodes.cityBlock_04_Lamp003.geometry}
          position={[4501.75, 961.41, -1735.14]}
          rotation={[-Math.PI / 2, 0, 0]}
          scale={[2.54, 2.54, 2.54]}
        />
        <mesh
          material={materials.MAT_METAL_1}
          geometry={nodes.cityBlock_04_Lamp_Light004.geometry}
          position={[9947.51, 961.41, -1735.14]}
          rotation={[-Math.PI / 2, 0, 0]}
          scale={[2.54, 2.54, 2.54]}
        />
        <mesh
          material={materials['Window Edging']}
          geometry={nodes.cityBlock_04_Lamp004.geometry}
          position={[9947.51, 961.41, -1735.14]}
          rotation={[-Math.PI / 2, 0, 0]}
          scale={[2.54, 2.54, 2.54]}
        />
      </group>
    </group>
  );
}

useGLTF.preload('/modelX.glb');
