/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
author: ConradJustin (https://sketchfab.com/ConradJustin)
license: CC-BY-4.0 (http://creativecommons.org/licenses/by/4.0/)
source: https://sketchfab.com/3d-models/chinese-tent-gift-ef9d7a2734284ed3b348f53f52e21cd4
title: Chinese tent (gift)
*/

import React, { useRef } from 'react';
import { useGLTF } from '@react-three/drei/useGLTF';

export default function Tent(props) {
  const group = useRef();
  const { nodes, materials } = useGLTF('/scene.gltf','/textures/');
  return (
    <group ref={group} {...props} dispose={null}>
      <group rotation={[-Math.PI / 2, 0, 0]}>
        <group position={[-148.11, 5.48, -427.31]} rotation={[Math.PI, 0, 3.1]}>
          <group rotation={[-Math.PI, 0, 0]}>
            <group position={[-78.83, 503.19, -354.38]} rotation={[1.57, -1.34, -1.72]} scale={[100, 100, 100]}>
              <mesh material={materials.Props} geometry={nodes.props_LOW_Props_0.geometry} />
              <mesh material={materials.floors} geometry={nodes.props_LOW_floors_0.geometry} />
              <mesh material={materials.tent} geometry={nodes.props_LOW_tent_0.geometry} />
            </group>
            <group position={[-78.83, 503.19, -354.38]} rotation={[1.57, -1.34, -1.72]} scale={[100, 100, 100]}>
              <mesh material={materials.tent} geometry={nodes.Tent_tutorial_tent_0.geometry} />
              <mesh material={materials.Props} geometry={nodes.Tent_tutorial_Props_0.geometry} />
              <mesh material={materials.floors} geometry={nodes.Tent_tutorial_floors_0.geometry} />
            </group>
          </group>
        </group>
      </group>
    </group>
  );
}

useGLTF.preload('/scene.gltf');
